CREATE TABLE `station` (
  `id` bigint(20) NOT NULL,
  `train_no` varchar(10) NOT NULL COMMENT '车次ID',
  `type` varchar(10) DEFAULT NULL COMMENT '列车类型',
  `station` varchar(64) NOT NULL COMMENT '车站名称',
  `sequence_no` varchar(10) DEFAULT NULL COMMENT '站序',
  `day` varchar(10) DEFAULT NULL COMMENT '天数',
  `arrival_time` varchar(20) DEFAULT NULL COMMENT '到达时间',
  `departure_time` varchar(20) DEFAULT NULL COMMENT '出发时间',
  `stop_time` varchar(20) DEFAULT NULL COMMENT '停留时间',
  `cost_time` varchar(20) DEFAULT NULL COMMENT '用时',
  `distance` varchar(10) DEFAULT NULL COMMENT '距离',
  `isend` int(1) DEFAULT NULL COMMENT '是否终点',
  `pricesw` varchar(10) DEFAULT NULL COMMENT '商务座票价',
  `pricetd` varchar(10) DEFAULT NULL COMMENT '特等座票价',
  `pricegr1` varchar(10) DEFAULT NULL COMMENT '高级软卧上票价',
  `pricegr2` varchar(10) DEFAULT NULL COMMENT '高级软卧下票价',
  `pricerw1` varchar(10) DEFAULT NULL COMMENT '软卧上票价',
  `pricerw2` varchar(10) DEFAULT NULL COMMENT '软卧下票价',
  `priceyw1` varchar(10) DEFAULT NULL COMMENT '硬卧上票价',
  `priceyw2` varchar(10) DEFAULT NULL COMMENT '硬卧中票价',
  `priceyw3` varchar(10) DEFAULT NULL COMMENT '硬卧下票价',
  `priceyd` varchar(10) DEFAULT NULL COMMENT '一等座票价',
  `priceed` varchar(10) DEFAULT NULL COMMENT '二等座票价',
  `create_time` timestamp(6) NULL DEFAULT NULL,
  `update_time` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

